version: '2.2'

services:
  dl-app:
    container_name: dl-app
    image: kyoungho/hello-distributed-logger:latest
    volumes:
      - ./fluentbit/rti_license.dat:/app/rti_license.dat
    network_mode: host

  fluentbit-out:
    container_name: fluentbit-out
    image: kyoungho/fluent-bit:latest
    volumes:
      - ./fluentbit/dds-out.conf:/app/fluent-bit.conf:ro
      - ./fluentbit/parsers.conf:/app/parsers.conf
      - ./fluentbit/rti_license.dat:/app/rti_license.dat
      - ./fluentbit/fluent_out_qos_profile.xml:/app/USER_QOS_PROFILES.xml
    privileged: true
    pid: host
    network_mode: host

  fluentbit-in:
    container_name: fluentbit-in
    image: kyoungho/fluent-bit:latest
    volumes:
      - ./fluentbit/dds-in.conf:/app/fluent-bit.conf:ro
      - ./fluentbit/rti_license.dat:/app/rti_license.dat
      - ./fluentbit/fluent_in_qos_profile.xml:/app/USER_QOS_PROFILES.xml
    network_mode: host

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
      - 5601:5601
    networks:
      - esnet

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      # mkdir ./esdata && chown 1000:1000 ./esdata
      - ./esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # mkdir -p $HOME/docker/influxdb/data
      - $HOME/docker/influxdb/data:/var/lib/influxdb
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      # Data persistency
      # mkdir -p $HOME/docker/grafana/data; sudo chown 472:472 $HOME/docker/grafana/data
      - $HOME/docker/grafana/data:/var/lib/grafana
    network_mode: host

networks:
  esnet:
