version: '2.2'

services:
  fluentbit-out:
    container_name: fluentbit-out
    image: kyoungho/fluent-bit:latest
    volumes:
      - ./fluentbit/dds-out.conf:/app/fluent-bit.conf:ro
      - ./fluentbit/rti_license.dat:/app/rti_license.dat
    networks:
      - esnet

  fluentbit-in:
    container_name: fluentbit-in
    image: kyoungho/fluent-bit:latest
    volumes:
      - ./fluentbit/dds-in.conf:/app/fluent-bit.conf:ro
      - ./fluentbit/rti_license.dat:/app/rti_license.dat
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
      - 5601:5601
    networks:
      - esnet

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=docker-
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
      
networks:
  esnet:
