version: '2.2'

services:

  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluentbit/td-agent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
      - 5601:5601
    networks:
      - esnet

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=docker-
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
      
networks:
  esnet:
